use ETL1;
/*                                                 Healthcare Data Analyis                                                                     */

select*from health_care;

-- 1. Retrieve the names of all patients in the database
select name from health_care;

-- 2. List the unique medical conditions present in dataset

select distinct(medical_condition) from health_care;

-- 3. Find the total number of doctors in the health care system
select count(distinct(doctor)) from health_care; 

-- 4. Retrieve the details of all female patients.
select*from health_care where gender='female';

-- 5. what is the average age of patients in the Database
select round(avg(age)) from health_care; 

-- 6. Identify the patients who have more than one medical condition.
select name,count(medical_condition) as num_condition from health_care
                      group by name having count(medical_condition)>1;

-- 7. List the names of all doctors.
select doctor from health_care;

-- 8.Identify the most common medical condition among patients.
select medical_condition,count(medical_condition) as common_condition
                          from health_care group by medical_condition 
                          order by common_condition desc limit 1;

-- 9.Find the patients who are older than 60 years and have diabets 
select*from health_care where age>60 and medical_condition='Diabetes';

-- 10.Calculate the total revenue generated by the healthcare system.
select round(sum(`billing amount`)) as revenue from health_care;


-- 11.Find the doctor with the oldest patient.
select doctor,age,name from health_care order by age desc limit 1;

-- 12.Calculate the average duration of medical visit
select round(avg(datediff(`discharge date`,`date of admission`)))+1 as medical_visit from health_care;

-- 13.Give the names of patients whose name starts with 'A'
select name from health_care where name like 'a%';

-- 14.How many male and female patients are there in dataset
select gender,count(gender) as `Number of Female and Male` 
       from health_care 
       group by gender having count(distinct(gender));

-- 15.how many patients are normal.
select `test results`,count(`test results`) as `normal patients` from health_care 
                            where `test results`='Normal' 
                            group by `test results` having count(distinct(`test results`));

-- 16.how many patients are abnormal or inconclusive
select `test results`,count(`test results`) as `abnormal and inconculsive` from health_care
          where `test results`='abnormal' or `test results`='inconclusive' 
          group by `test results` having count(distinct(`test results`));

-- 17.how many patients of blood group AB+ are there of age above 52.
select*from health_care;
select `blood type`,count(`blood type`) as `count ab+ above 52 age` from health_care
              where `blood type`='ab+' and age>52
              group by `blood type` having count(distinct(`blood type`));  
              
-- 18. how many patients have paid the bill above 24890.
select count(`billing amount`) from health_care where `billing amount`>24890;


-- 19. what are the names of patients having Asthma
select name,medical_condition from health_care where medical_condition='Asthma';

-- 20. how many patients have cancer.
select medical_condition,count(medical_condition) as `no of cancer patients` 
                           from health_care where medical_condition='cancer'
                           group by medical_condition having count(distinct(medical_condition)); 
                           
-- 21. what are the names and blood groups of patients admitted to room no. 292.
select `blood type`,name,`room number` from health_care where `room number`=292;

-- 22. how many males have Arthritis.
select gender,count(gender) as `male who has arthritis` from health_care 
                   where medical_condition='arthritis' and gender='male' 
                   group by gender having count(distinct(gender));
                   
-- 23. How many patients were admitted to Harris and Sons hospital.
select*from health_care;
select hospital,count(hospital) as `harris and Sons` from health_care 
					where hospital='harris and sons' 
					group by hospital having count(distinct(hospital));
                    
-- 24. what are the names of patients whose Insurance Provider are Cigna.
select name,`insurance provider` from health_care where `Insurance Provider`='cigna';

-- 25. Name the Medical Condition having patients whose ages is greater than average age
select medical_condition,age from health_care where age>(select avg(age) from health_care ) ;

-- 26.Which hospital has the highest number of patients?
select hospital,count(hospital) as `hospital highest paitent` from health_care group by hospital having count(distinct(hospital)); 

-- 27.What are the most common admission types ?
select `admission type`,count(`admission type`) from health_care group by `admission type` having count(distinct(`admission type`));

-- 28.What are the most commonly prescribed medications?
select medication,count(medication) from health_care group by medication having count(distinct(medication)); 

-- 29.How do admission patterns change over time by sesons?
-- analyzing trends by month
select month(`date of admission`) as month ,count(`date of admission`) as admission_count 
                       from health_care group by month(`date of admission`) order by month; 

-- analyzing trends by calculender week and sesons
WITH seasons AS (
  SELECT
    `date of admission`,
    CASE
      WHEN MONTH(`date of admission`) IN (12, 1, 2) THEN 'Winter'
      WHEN MONTH(`date of admission`) IN (3, 4, 5) THEN 'Spring'
      WHEN MONTH(`date of admission`) IN (6, 7, 8) THEN 'Summer'
      ELSE 'Autumn'
    END AS season
  FROM health_care
),
weekly_counts AS (
  SELECT
    season,
    WEEK(`date of admission`, 1) AS week_number,
    COUNT(`date of admission`) AS admissions_count
  FROM seasons
  GROUP BY season, WEEK(`date of admission`, 1)
)
SELECT season, week_number, admissions_count
FROM weekly_counts
ORDER BY season, week_number;

-- 30.show the billing amount of the patient greater than avg billing amount
select name,`billing amount`from health_care where `billing amount` >(select round(avg(`billing amount`)) from health_care);

-- 31.Count the number of patient with a `billing amount` higher than the higher `billing amount` of the insurance provider as 'medicare
select count(*) from health_care where `insurance provider`='medicare' and `billing amount` >(select avg(`billing amount`) from health_care );
select*from health_care;
-- 32.show the patient with a `billing amount` higher than the higher `billing amount` of the Insurance Provider as 'Medicare'
select*from health_care where `insurance provider`='medicare' and `billing amount` > (select avg(`billing amount`) from health_care );

-- 32.list the patient who is billing amount is greater than avg billing amount with second oldest patient
select*from health_care where `billing amount` >(select avg(`billing amount`) from health_care) order by age desc limit 1,1;


